name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Components
      run: rustup component add rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo fmt --check
        cargo test --verbose
